	wasca u0 (
		.abus_slave_0_abus_address                      (<connected-to-abus_slave_0_abus_address>),                      //                 abus_slave_0_abus.address
		.abus_slave_0_abus_chipselect                   (<connected-to-abus_slave_0_abus_chipselect>),                   //                                  .chipselect
		.abus_slave_0_abus_read                         (<connected-to-abus_slave_0_abus_read>),                         //                                  .read
		.abus_slave_0_abus_write                        (<connected-to-abus_slave_0_abus_write>),                        //                                  .write
		.abus_slave_0_abus_waitrequest                  (<connected-to-abus_slave_0_abus_waitrequest>),                  //                                  .waitrequest
		.abus_slave_0_abus_interrupt                    (<connected-to-abus_slave_0_abus_interrupt>),                    //                                  .interrupt
		.abus_slave_0_abus_addressdata                  (<connected-to-abus_slave_0_abus_addressdata>),                  //                                  .addressdata
		.abus_slave_0_abus_direction                    (<connected-to-abus_slave_0_abus_direction>),                    //                                  .direction
		.abus_slave_0_abus_muxing                       (<connected-to-abus_slave_0_abus_muxing>),                       //                                  .muxing
		.abus_slave_0_abus_disableout                   (<connected-to-abus_slave_0_abus_disableout>),                   //                                  .disableout
		.abus_slave_0_conduit_saturn_reset_saturn_reset (<connected-to-abus_slave_0_conduit_saturn_reset_saturn_reset>), // abus_slave_0_conduit_saturn_reset.saturn_reset
		.altpll_0_areset_conduit_export                 (<connected-to-altpll_0_areset_conduit_export>),                 //           altpll_0_areset_conduit.export
		.altpll_0_locked_conduit_export                 (<connected-to-altpll_0_locked_conduit_export>),                 //           altpll_0_locked_conduit.export
		.altpll_0_phasedone_conduit_export              (<connected-to-altpll_0_phasedone_conduit_export>),              //        altpll_0_phasedone_conduit.export
		.clk_clk                                        (<connected-to-clk_clk>),                                        //                               clk.clk
		.external_sdram_controller_wire_addr            (<connected-to-external_sdram_controller_wire_addr>),            //    external_sdram_controller_wire.addr
		.external_sdram_controller_wire_ba              (<connected-to-external_sdram_controller_wire_ba>),              //                                  .ba
		.external_sdram_controller_wire_cas_n           (<connected-to-external_sdram_controller_wire_cas_n>),           //                                  .cas_n
		.external_sdram_controller_wire_cke             (<connected-to-external_sdram_controller_wire_cke>),             //                                  .cke
		.external_sdram_controller_wire_cs_n            (<connected-to-external_sdram_controller_wire_cs_n>),            //                                  .cs_n
		.external_sdram_controller_wire_dq              (<connected-to-external_sdram_controller_wire_dq>),              //                                  .dq
		.external_sdram_controller_wire_dqm             (<connected-to-external_sdram_controller_wire_dqm>),             //                                  .dqm
		.external_sdram_controller_wire_ras_n           (<connected-to-external_sdram_controller_wire_ras_n>),           //                                  .ras_n
		.external_sdram_controller_wire_we_n            (<connected-to-external_sdram_controller_wire_we_n>),            //                                  .we_n
		.extra_leds_conn_export                         (<connected-to-extra_leds_conn_export>),                         //                   extra_leds_conn.export
		.hex0_conn_export                               (<connected-to-hex0_conn_export>),                               //                         hex0_conn.export
		.hex1_conn_export                               (<connected-to-hex1_conn_export>),                               //                         hex1_conn.export
		.hex2_conn_export                               (<connected-to-hex2_conn_export>),                               //                         hex2_conn.export
		.hex3_conn_export                               (<connected-to-hex3_conn_export>),                               //                         hex3_conn.export
		.hex4_conn_export                               (<connected-to-hex4_conn_export>),                               //                         hex4_conn.export
		.hex5_conn_export                               (<connected-to-hex5_conn_export>),                               //                         hex5_conn.export
		.hexdot_conn_export                             (<connected-to-hexdot_conn_export>),                             //                       hexdot_conn.export
		.leds_conn_export                               (<connected-to-leds_conn_export>),                               //                         leds_conn.export
		.sdram_clkout_clk                               (<connected-to-sdram_clkout_clk>),                               //                      sdram_clkout.clk
		.spi_stm32_MISO                                 (<connected-to-spi_stm32_MISO>),                                 //                         spi_stm32.MISO
		.spi_stm32_MOSI                                 (<connected-to-spi_stm32_MOSI>),                                 //                                  .MOSI
		.spi_stm32_SCLK                                 (<connected-to-spi_stm32_SCLK>),                                 //                                  .SCLK
		.spi_stm32_SS_n                                 (<connected-to-spi_stm32_SS_n>),                                 //                                  .SS_n
		.spi_sync_conn_export                           (<connected-to-spi_sync_conn_export>),                           //                     spi_sync_conn.export
		.switches_conn_export                           (<connected-to-switches_conn_export>),                           //                     switches_conn.export
		.uart_0_external_connection_rxd                 (<connected-to-uart_0_external_connection_rxd>),                 //        uart_0_external_connection.rxd
		.uart_0_external_connection_txd                 (<connected-to-uart_0_external_connection_txd>)                  //                                  .txd
	);

