# TCL File Generated by Component Editor 15.1
# Sun Dec 15 11:49:47 JST 2019
# DO NOT MODIFY


# 
# abus_demux "abus_demux" v1.1
#  2019.12.15.11:49:47
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module abus_demux
# 
set_module_property DESCRIPTION ""
set_module_property NAME abus_demux
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME abus_demux
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL abus_demux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file abus_demux.vhd VHDL PATH abus_demux.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL abus_demux
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file abus_demux.vhd VHDL PATH abus_demux.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point abus
# 
add_interface abus conduit end
set_interface_property abus associatedClock ""
set_interface_property abus associatedReset ""
set_interface_property abus ENABLED true
set_interface_property abus EXPORT_OF ""
set_interface_property abus PORT_NAME_MAP ""
set_interface_property abus CMSIS_SVD_VARIABLES ""
set_interface_property abus SVD_ADDRESS_GROUP ""

add_interface_port abus abus_address address Input 10
add_interface_port abus abus_chipselect chipselect Input 3
add_interface_port abus abus_read read Input 1
add_interface_port abus abus_write write Input 2
add_interface_port abus abus_waitrequest waitrequest Output 1
add_interface_port abus abus_interrupt interrupt Output 1
add_interface_port abus abus_addressdata addressdata Bidir 16
add_interface_port abus abus_direction direction Output 1
add_interface_port abus abus_muxing muxing Output 2
add_interface_port abus abus_disable_out disableout Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_nios
# 
add_interface avalon_nios avalon end
set_interface_property avalon_nios addressUnits WORDS
set_interface_property avalon_nios associatedClock clock
set_interface_property avalon_nios associatedReset reset
set_interface_property avalon_nios bitsPerSymbol 8
set_interface_property avalon_nios burstOnBurstBoundariesOnly false
set_interface_property avalon_nios burstcountUnits WORDS
set_interface_property avalon_nios explicitAddressSpan 0
set_interface_property avalon_nios holdTime 0
set_interface_property avalon_nios linewrapBursts false
set_interface_property avalon_nios maximumPendingReadTransactions 1
set_interface_property avalon_nios maximumPendingWriteTransactions 0
set_interface_property avalon_nios readLatency 0
set_interface_property avalon_nios readWaitTime 1
set_interface_property avalon_nios setupTime 0
set_interface_property avalon_nios timingUnits Cycles
set_interface_property avalon_nios writeWaitTime 0
set_interface_property avalon_nios ENABLED true
set_interface_property avalon_nios EXPORT_OF ""
set_interface_property avalon_nios PORT_NAME_MAP ""
set_interface_property avalon_nios CMSIS_SVD_VARIABLES ""
set_interface_property avalon_nios SVD_ADDRESS_GROUP ""

add_interface_port avalon_nios avalon_nios_read read Input 1
add_interface_port avalon_nios avalon_nios_write write Input 1
add_interface_port avalon_nios avalon_nios_address address Input 8
add_interface_port avalon_nios avalon_nios_writedata writedata Input 32
add_interface_port avalon_nios avalon_nios_readdata readdata Output 32
add_interface_port avalon_nios avalon_nios_waitrequest waitrequest Output 1
add_interface_port avalon_nios avalon_nios_readdatavalid readdatavalid Output 1
add_interface_port avalon_nios avalon_nios_burstcount burstcount Input 1
set_interface_assignment avalon_nios embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_nios embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_nios embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_nios embeddedsw.configuration.isPrintableDevice 0


# 
# connection point demux
# 
add_interface demux conduit end
set_interface_property demux associatedClock clock
set_interface_property demux associatedReset ""
set_interface_property demux ENABLED true
set_interface_property demux EXPORT_OF ""
set_interface_property demux PORT_NAME_MAP ""
set_interface_property demux CMSIS_SVD_VARIABLES ""
set_interface_property demux SVD_ADDRESS_GROUP ""

add_interface_port demux demux_writeaddress writeaddress Output 28
add_interface_port demux demux_writedata data Output 16
add_interface_port demux demux_writepulse writepulse Output 1
add_interface_port demux demux_write_byteenable write_byteenable Output 2
add_interface_port demux demux_readdata readdata Input 16
add_interface_port demux demux_readpulse readpulse Output 1
add_interface_port demux demux_readdatavalid readdatavalid Input 1
add_interface_port demux demux_readaddress readaddress Output 28


# 
# connection point conduit_saturn_reset
# 
add_interface conduit_saturn_reset conduit end
set_interface_property conduit_saturn_reset associatedClock clock
set_interface_property conduit_saturn_reset associatedReset ""
set_interface_property conduit_saturn_reset ENABLED true
set_interface_property conduit_saturn_reset EXPORT_OF ""
set_interface_property conduit_saturn_reset PORT_NAME_MAP ""
set_interface_property conduit_saturn_reset CMSIS_SVD_VARIABLES ""
set_interface_property conduit_saturn_reset SVD_ADDRESS_GROUP ""

add_interface_port conduit_saturn_reset saturn_reset saturn_reset Input 1

