# TCL File Generated by Component Editor 15.1
# Sat May 02 17:39:58 JST 2020
# DO NOT MODIFY


# 
# abus_slave "abus_slave" v1.2
#  2020.05.02.17:39:58
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module abus_slave
# 
set_module_property DESCRIPTION ""
set_module_property NAME abus_slave
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME abus_slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL abus_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file abus_slave.vhd VHDL PATH abus_slave.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL abus_slave
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file abus_slave.vhd VHDL PATH abus_slave.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avalon_read read Output 1
add_interface_port avalon_master avalon_write write Output 1
add_interface_port avalon_master avalon_waitrequest waitrequest Input 1
add_interface_port avalon_master avalon_address address Output 28
add_interface_port avalon_master avalon_readdata readdata Input 16
add_interface_port avalon_master avalon_writedata writedata Output 16
add_interface_port avalon_master avalon_readdatavalid readdatavalid Input 1
add_interface_port avalon_master avalon_burstcount burstcount Output 1
add_interface_port avalon_master avalon_byteenable byteenable Output 2


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_nios
# 
add_interface avalon_nios avalon end
set_interface_property avalon_nios addressUnits WORDS
set_interface_property avalon_nios associatedClock clock
set_interface_property avalon_nios associatedReset reset
set_interface_property avalon_nios bitsPerSymbol 8
set_interface_property avalon_nios burstOnBurstBoundariesOnly false
set_interface_property avalon_nios burstcountUnits WORDS
set_interface_property avalon_nios explicitAddressSpan 0
set_interface_property avalon_nios holdTime 0
set_interface_property avalon_nios linewrapBursts false
set_interface_property avalon_nios maximumPendingReadTransactions 1
set_interface_property avalon_nios maximumPendingWriteTransactions 0
set_interface_property avalon_nios readLatency 0
set_interface_property avalon_nios readWaitTime 1
set_interface_property avalon_nios setupTime 0
set_interface_property avalon_nios timingUnits Cycles
set_interface_property avalon_nios writeWaitTime 0
set_interface_property avalon_nios ENABLED true
set_interface_property avalon_nios EXPORT_OF ""
set_interface_property avalon_nios PORT_NAME_MAP ""
set_interface_property avalon_nios CMSIS_SVD_VARIABLES ""
set_interface_property avalon_nios SVD_ADDRESS_GROUP ""

add_interface_port avalon_nios avalon_nios_read read Input 1
add_interface_port avalon_nios avalon_nios_write write Input 1
add_interface_port avalon_nios avalon_nios_address address Input 8
add_interface_port avalon_nios avalon_nios_writedata writedata Input 32
add_interface_port avalon_nios avalon_nios_readdata readdata Output 32
add_interface_port avalon_nios avalon_nios_waitrequest waitrequest Output 1
add_interface_port avalon_nios avalon_nios_readdatavalid readdatavalid Output 1
add_interface_port avalon_nios avalon_nios_burstcount burstcount Input 1
set_interface_assignment avalon_nios embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_nios embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_nios embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_nios embeddedsw.configuration.isPrintableDevice 0


# 
# connection point demux
# 
add_interface demux conduit end
set_interface_property demux associatedClock clock
set_interface_property demux associatedReset ""
set_interface_property demux ENABLED true
set_interface_property demux EXPORT_OF ""
set_interface_property demux PORT_NAME_MAP ""
set_interface_property demux CMSIS_SVD_VARIABLES ""
set_interface_property demux SVD_ADDRESS_GROUP ""

add_interface_port demux demux_writeaddress writeaddress Input 28
add_interface_port demux demux_writedata data Input 16
add_interface_port demux demux_writepulse writepulse Input 1
add_interface_port demux demux_write_byteenable write_byteenable Input 2
add_interface_port demux demux_readdata readdata Output 16
add_interface_port demux demux_readpulse readpulse Input 1
add_interface_port demux demux_readdatavalid readdatavalid Output 1
add_interface_port demux demux_readaddress readaddress Input 28


# 
# connection point avalon_trace
# 
add_interface avalon_trace avalon start
set_interface_property avalon_trace addressUnits SYMBOLS
set_interface_property avalon_trace associatedClock clock
set_interface_property avalon_trace associatedReset reset
set_interface_property avalon_trace bitsPerSymbol 8
set_interface_property avalon_trace burstOnBurstBoundariesOnly false
set_interface_property avalon_trace burstcountUnits WORDS
set_interface_property avalon_trace doStreamReads false
set_interface_property avalon_trace doStreamWrites false
set_interface_property avalon_trace holdTime 0
set_interface_property avalon_trace linewrapBursts false
set_interface_property avalon_trace maximumPendingReadTransactions 0
set_interface_property avalon_trace maximumPendingWriteTransactions 0
set_interface_property avalon_trace readLatency 0
set_interface_property avalon_trace readWaitTime 1
set_interface_property avalon_trace setupTime 0
set_interface_property avalon_trace timingUnits Cycles
set_interface_property avalon_trace writeWaitTime 0
set_interface_property avalon_trace ENABLED true
set_interface_property avalon_trace EXPORT_OF ""
set_interface_property avalon_trace PORT_NAME_MAP ""
set_interface_property avalon_trace CMSIS_SVD_VARIABLES ""
set_interface_property avalon_trace SVD_ADDRESS_GROUP ""

add_interface_port avalon_trace avalon_trace_address address Output 28
add_interface_port avalon_trace avalon_trace_burstcount burstcount Output 1
add_interface_port avalon_trace avalon_trace_byteenable byteenable Output 8
add_interface_port avalon_trace avalon_trace_read read Output 1
add_interface_port avalon_trace avalon_trace_readdata readdata Input 64
add_interface_port avalon_trace avalon_trace_readdatavalid readdatavalid Input 1
add_interface_port avalon_trace avalon_trace_waitrequest waitrequest Input 1
add_interface_port avalon_trace avalon_trace_write write Output 1
add_interface_port avalon_trace avalon_trace_writedata writedata Output 64

