// wasca_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.1 193

`timescale 1 ps / 1 ps
module wasca_mm_interconnect_1 (
		input  wire        altpll_0_c0_clk,                                //                              altpll_0_c0.clk
		input  wire        abus_slave_0_reset_reset_bridge_in_reset_reset, // abus_slave_0_reset_reset_bridge_in_reset.reset
		input  wire [27:0] abus_slave_0_avalon_trace_address,              //                abus_slave_0_avalon_trace.address
		output wire        abus_slave_0_avalon_trace_waitrequest,          //                                         .waitrequest
		input  wire [0:0]  abus_slave_0_avalon_trace_burstcount,           //                                         .burstcount
		input  wire [7:0]  abus_slave_0_avalon_trace_byteenable,           //                                         .byteenable
		input  wire        abus_slave_0_avalon_trace_read,                 //                                         .read
		output wire [63:0] abus_slave_0_avalon_trace_readdata,             //                                         .readdata
		output wire        abus_slave_0_avalon_trace_readdatavalid,        //                                         .readdatavalid
		input  wire        abus_slave_0_avalon_trace_write,                //                                         .write
		input  wire [63:0] abus_slave_0_avalon_trace_writedata,            //                                         .writedata
		output wire [8:0]  onchip_trace_mem_s1_address,                    //                      onchip_trace_mem_s1.address
		output wire        onchip_trace_mem_s1_write,                      //                                         .write
		input  wire [63:0] onchip_trace_mem_s1_readdata,                   //                                         .readdata
		output wire [63:0] onchip_trace_mem_s1_writedata,                  //                                         .writedata
		output wire [7:0]  onchip_trace_mem_s1_byteenable,                 //                                         .byteenable
		output wire        onchip_trace_mem_s1_chipselect,                 //                                         .chipselect
		output wire        onchip_trace_mem_s1_clken                       //                                         .clken
	);

	wire         abus_slave_0_avalon_trace_translator_avalon_universal_master_0_waitrequest;   // onchip_trace_mem_s1_translator:uav_waitrequest -> abus_slave_0_avalon_trace_translator:uav_waitrequest
	wire  [63:0] abus_slave_0_avalon_trace_translator_avalon_universal_master_0_readdata;      // onchip_trace_mem_s1_translator:uav_readdata -> abus_slave_0_avalon_trace_translator:uav_readdata
	wire         abus_slave_0_avalon_trace_translator_avalon_universal_master_0_debugaccess;   // abus_slave_0_avalon_trace_translator:uav_debugaccess -> onchip_trace_mem_s1_translator:uav_debugaccess
	wire  [27:0] abus_slave_0_avalon_trace_translator_avalon_universal_master_0_address;       // abus_slave_0_avalon_trace_translator:uav_address -> onchip_trace_mem_s1_translator:uav_address
	wire         abus_slave_0_avalon_trace_translator_avalon_universal_master_0_read;          // abus_slave_0_avalon_trace_translator:uav_read -> onchip_trace_mem_s1_translator:uav_read
	wire   [7:0] abus_slave_0_avalon_trace_translator_avalon_universal_master_0_byteenable;    // abus_slave_0_avalon_trace_translator:uav_byteenable -> onchip_trace_mem_s1_translator:uav_byteenable
	wire         abus_slave_0_avalon_trace_translator_avalon_universal_master_0_readdatavalid; // onchip_trace_mem_s1_translator:uav_readdatavalid -> abus_slave_0_avalon_trace_translator:uav_readdatavalid
	wire         abus_slave_0_avalon_trace_translator_avalon_universal_master_0_lock;          // abus_slave_0_avalon_trace_translator:uav_lock -> onchip_trace_mem_s1_translator:uav_lock
	wire         abus_slave_0_avalon_trace_translator_avalon_universal_master_0_write;         // abus_slave_0_avalon_trace_translator:uav_write -> onchip_trace_mem_s1_translator:uav_write
	wire  [63:0] abus_slave_0_avalon_trace_translator_avalon_universal_master_0_writedata;     // abus_slave_0_avalon_trace_translator:uav_writedata -> onchip_trace_mem_s1_translator:uav_writedata
	wire   [3:0] abus_slave_0_avalon_trace_translator_avalon_universal_master_0_burstcount;    // abus_slave_0_avalon_trace_translator:uav_burstcount -> onchip_trace_mem_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (28),
		.AV_DATA_W                   (64),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (8),
		.UAV_ADDRESS_W               (28),
		.UAV_BURSTCOUNT_W            (4),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (8),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) abus_slave_0_avalon_trace_translator (
		.clk                    (altpll_0_c0_clk),                                                              //                       clk.clk
		.reset                  (abus_slave_0_reset_reset_bridge_in_reset_reset),                               //                     reset.reset
		.uav_address            (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (abus_slave_0_avalon_trace_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (abus_slave_0_avalon_trace_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (abus_slave_0_avalon_trace_burstcount),                                         //                          .burstcount
		.av_byteenable          (abus_slave_0_avalon_trace_byteenable),                                         //                          .byteenable
		.av_read                (abus_slave_0_avalon_trace_read),                                               //                          .read
		.av_readdata            (abus_slave_0_avalon_trace_readdata),                                           //                          .readdata
		.av_readdatavalid       (abus_slave_0_avalon_trace_readdatavalid),                                      //                          .readdatavalid
		.av_write               (abus_slave_0_avalon_trace_write),                                              //                          .write
		.av_writedata           (abus_slave_0_avalon_trace_writedata),                                          //                          .writedata
		.av_beginbursttransfer  (1'b0),                                                                         //               (terminated)
		.av_begintransfer       (1'b0),                                                                         //               (terminated)
		.av_chipselect          (1'b0),                                                                         //               (terminated)
		.av_lock                (1'b0),                                                                         //               (terminated)
		.av_debugaccess         (1'b0),                                                                         //               (terminated)
		.uav_clken              (),                                                                             //               (terminated)
		.av_clken               (1'b1),                                                                         //               (terminated)
		.uav_response           (2'b00),                                                                        //               (terminated)
		.av_response            (),                                                                             //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                         //               (terminated)
		.av_writeresponsevalid  ()                                                                              //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (9),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (28),
		.UAV_BURSTCOUNT_W               (4),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) onchip_trace_mem_s1_translator (
		.clk                    (altpll_0_c0_clk),                                                              //                      clk.clk
		.reset                  (abus_slave_0_reset_reset_bridge_in_reset_reset),                               //                    reset.reset
		.uav_address            (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (abus_slave_0_avalon_trace_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (onchip_trace_mem_s1_address),                                                  //      avalon_anti_slave_0.address
		.av_write               (onchip_trace_mem_s1_write),                                                    //                         .write
		.av_readdata            (onchip_trace_mem_s1_readdata),                                                 //                         .readdata
		.av_writedata           (onchip_trace_mem_s1_writedata),                                                //                         .writedata
		.av_byteenable          (onchip_trace_mem_s1_byteenable),                                               //                         .byteenable
		.av_chipselect          (onchip_trace_mem_s1_chipselect),                                               //                         .chipselect
		.av_clken               (onchip_trace_mem_s1_clken),                                                    //                         .clken
		.av_read                (),                                                                             //              (terminated)
		.av_begintransfer       (),                                                                             //              (terminated)
		.av_beginbursttransfer  (),                                                                             //              (terminated)
		.av_burstcount          (),                                                                             //              (terminated)
		.av_readdatavalid       (1'b0),                                                                         //              (terminated)
		.av_waitrequest         (1'b0),                                                                         //              (terminated)
		.av_writebyteenable     (),                                                                             //              (terminated)
		.av_lock                (),                                                                             //              (terminated)
		.uav_clken              (1'b0),                                                                         //              (terminated)
		.av_debugaccess         (),                                                                             //              (terminated)
		.av_outputenable        (),                                                                             //              (terminated)
		.uav_response           (),                                                                             //              (terminated)
		.av_response            (2'b00),                                                                        //              (terminated)
		.uav_writeresponsevalid (),                                                                             //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                          //              (terminated)
	);

endmodule
